PresentationLayer/Controllers/DepartmentController.cs
using BusinessLogicLayer.Interfaces;
using BusinessLogicLayer.Repositories;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        //IDepartmentRepository DepartmentRepository;
        private readonly IUnitOfWorkRepository UnitOfWorkRepository;
        public DepartmentController(IUnitOfWorkRepository UnitOfWorkRepository)
        {
            //this.DepartmentRepository = DepartmentRepository;
            this.UnitOfWorkRepository = UnitOfWorkRepository;
        }
        public IActionResult Index()
        {
            List<Department> Departments = UnitOfWorkRepository.DepartmentRepository.GetAll();

            return View("AllDepartments", Departments);
        }

        public IActionResult Add()
        {
            return View("AddDepartment");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Department D)
        {
            if(ModelState.IsValid == true)
            {
                UnitOfWorkRepository.DepartmentRepository.Insert(D);
                UnitOfWorkRepository.DepartmentRepository.SaveChanges();

                return RedirectToAction("Index");
            }

            return View("AddDepartment", D);
        }

        public IActionResult Details(int id)
        {
            Department Department = UnitOfWorkRepository.DepartmentRepository.GetById(id);

            return View("DepartmentDetails", Department);
        }

        public IActionResult Update(int id)
        {
            Department Department = UnitOfWorkRepository.DepartmentRepository.GetById(id);

            return View("UpdateDepartment", Department);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEdit(Department D, int id)
        {
            if(D.Name != null && D.Code != null)
            {
                UnitOfWorkRepository.DepartmentRepository.Edit(id, D);
                UnitOfWorkRepository.DepartmentRepository.SaveChanges();

                return RedirectToAction("Index");
            }

            return View("UpdateDepartment", D);
        }

        public IActionResult Delete(int id)
        {
            Department Department = UnitOfWorkRepository.DepartmentRepository.GetById(id);

            return View("DeleteDepartment", Department);
        }

        public IActionResult SaveDelete (int id)
        {
            UnitOfWorkRepository.DepartmentRepository.Delete(id);
            UnitOfWorkRepository.DepartmentRepository.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult CheckName(string Name)
        {
            bool Flag = UnitOfWorkRepository.DepartmentRepository.CheckUnique(Name);

            if(Flag)
            {
                return Json(true);
            }

            return Json(false);
        }

        // For Just Test
        [Route("emp/{Name:alpha}")]
        // OR : [HttpGet("emp/{Name:alpha}")]
        public IActionResult ActionRoute(string Name)
        {
            return Content($"This Name : {Name}");
        }
    }
}

PresentationLayer/Controllers/EmployeeController.cs
using AutoMapper;
using BusinessLogicLayer.Interfaces;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Controllers.Helpers;
using PresentationLayer.Models.ViewModels;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        //private readonly IEmployeeRepository EmployeeRepository;
        //private readonly IDepartmentRepository DepartmentRepository;
        //private readonly IMapper mapper;

        private readonly IUnitOfWorkRepository UnitOfWorkRepository;
        private readonly FileHelper Helper;

        public EmployeeController(IUnitOfWorkRepository UnitOfWorkRepository /*,IMapper Mapper*/,
                                  FileHelper Helper)
        {
            // Injection
            this.UnitOfWorkRepository = UnitOfWorkRepository;
            this.Helper = Helper;
            //mapper = Mapper;
        }
        public IActionResult Index(string Word)
        {
            List<Employee> Employees = new List<Employee>();

            if(Word == null)
            {
                Employees = UnitOfWorkRepository.EmployeeRepository.GetAll();
            }
            else
            {
                Employees = UnitOfWorkRepository.EmployeeRepository.GetAllByName(Word);
            }

            return View(Employees);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Departments = UnitOfWorkRepository.DepartmentRepository.GetAll();

            // Just Example For Practice
            //Department D = new Department();
            //var Result = mapper.Map<Employee>(D);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Employee Emp, IFormFile? Image)
        {
            if (ModelState.IsValid == true)
            {
                if (Emp.DeptId != -1)
                {
                    if(Image != null)
                    {
                        FileViewModel FileModel = new FileViewModel();

                        FileModel = Helper.StoreFile(Image, "Images");

                        Emp.ImageNameWithGuid = FileModel.FileNameWithGuid;
                        Emp.ImageName = FileModel.FileName;
                    }

                    UnitOfWorkRepository.EmployeeRepository.Insert(Emp);
                    UnitOfWorkRepository.EmployeeRepository.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("DeptId", "You Must Choose Department");
                }
            }

            ViewBag.Departments = UnitOfWorkRepository.DepartmentRepository.GetAll();

            return View("Add", Emp);
        }

        public IActionResult Details(int id)
        {
            Employee Emp = UnitOfWorkRepository.EmployeeRepository.GetById(id);

            return View(Emp);
        }

        public IActionResult Update(int id)
        {
            Employee Emp = UnitOfWorkRepository.EmployeeRepository.GetById(id);

            ViewBag.Departments = UnitOfWorkRepository.DepartmentRepository.GetAll();

            return View(Emp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Employee Emp, IFormFile Image)
        {
            if (ModelState.IsValid == true)
            {
                if (Emp.DeptId != -1)
                {
                    if(Image != null)
                    {
                        Employee EmpBefore = UnitOfWorkRepository.EmployeeRepository.GetById(id);

                        if(EmpBefore.ImageName != Image.FileName)
                        {
                            if(EmpBefore.ImageNameWithGuid != null)
                            {
                                Helper.DeleteFile(EmpBefore.ImageNameWithGuid, "Images");
                            }

                            FileViewModel FileModel = Helper.StoreFile(Image, "Images");
                            Emp.ImageName = FileModel.FileName;
                            Emp.ImageNameWithGuid = FileModel.FileNameWithGuid;
                        }
                    }

                    UnitOfWorkRepository.EmployeeRepository.Edit(id, Emp);
                    UnitOfWorkRepository.EmployeeRepository.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("DptId", "You Must Choose Department");
                }
            }

            ViewBag.Departments = UnitOfWorkRepository.DepartmentRepository.GetAll();

            return View("Update", Emp);
        }

        public IActionResult Delete(int id)
        {
            Employee Emp = UnitOfWorkRepository.EmployeeRepository.GetById(id);

            return View(Emp);
        }

        public IActionResult SaveDelete(int id)
        {
            Employee Emp = UnitOfWorkRepository.EmployeeRepository.GetById(id);
            if(Emp.ImageNameWithGuid != null)
            {
                Helper.DeleteFile(Emp.ImageNameWithGuid, "Images");
            }

            UnitOfWorkRepository.EmployeeRepository.Delete(id);
            UnitOfWorkRepository.EmployeeRepository.SaveChanges();

            return RedirectToAction("Index");
        }
    } 
}

PresentationLayer/Controllers/UserController.cs
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models.ViewModels;

namespace PresentationLayer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> UserManager;

        public UserController(UserManager<ApplicationUser> UserManager)
        {
            this.UserManager = UserManager;
        }

        public async Task<IActionResult> Index(string SearchWord)
        {
            List<UserViewModel> UsersVM = new List<UserViewModel>();
            List<ApplicationUser> Users = new List<ApplicationUser>();

            if (SearchWord == null)
            {
                Users = UserManager.Users.ToList();

                for (int i = 0; i < Users.Count(); ++i)
                {
                    UserViewModel User = new UserViewModel()
                    {
                        Id = Users[i].Id,
                        UserName = Users[i].UserName,
                        Email = Users[i].Email,
                        Roles = UserManager.GetRolesAsync(Users[i]).Result.ToList(),
                        Address = Users[i].Address
                    };

                    UsersVM.Add(User);
                }

                return View(UsersVM);
            }

            Users = UserManager.Users.Where(U => U.Email.ToLower().Contains(SearchWord.ToLower())).ToList();

            for(int i = 0; i < Users.Count(); ++i)
            {
                UserViewModel User = new UserViewModel()
                {
                    Id = Users[i].Id,
                    UserName = Users[i].UserName,
                    Email = Users[i].Email,
                    Roles = UserManager.GetRolesAsync(Users[i]).Result.ToList(),
                    Address = Users[i].Address
                };

                UsersVM.Add(User);
            }

            return View(UsersVM);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string Id)
        {
            ApplicationUser User = await UserManager.FindByIdAsync(Id);

            UserViewModel UserVM = new UserViewModel()
            {
                Id = User.Id,
                UserName = User.UserName,
                Email = User.Email,
                Roles = UserManager.GetRolesAsync(User).Result.ToList(),
                Address = User.Address
            };

            return View(UserVM);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string Id)
        {
            ApplicationUser User = await UserManager.FindByIdAsync(Id);

            UserViewModel UserVM = new UserViewModel()
            {
                Id = User.Id,
                UserName = User.UserName,
                Email = User.Email,
                Roles = UserManager.GetRolesAsync(User).Result.ToList(),
                Address = User.Address
            };

            return View(UserVM);
        }

        [HttpGet]
        public async Task<IActionResult> SaveDelete(string Id)
        {
            ApplicationUser User = await UserManager.FindByIdAsync(Id);

            UserViewModel UserVM = new UserViewModel()
            {
                Id = User.Id,
                UserName = User.UserName,
                Email = User.Email,
                Roles = UserManager.GetRolesAsync(User).Result.ToList(),
                Address = User.Address
            };

            IdentityResult Result = await UserManager.DeleteAsync(User);

            if(Result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            return View(UserVM);
        }

        [HttpGet]
        public async Task<IActionResult> Update(string Id)
        {
            ApplicationUser User = await UserManager.FindByIdAsync(Id);

            UserUpdateViewModel UserVM = new UserUpdateViewModel()
            {
                Id = User.Id,
                UserName = User.UserName,
                Email = User.Email,
                Address = User.Address
            };

            return View(UserVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UserUpdateViewModel Model)
        {
            if(ModelState.IsValid)
            {
                ApplicationUser User = await UserManager.FindByIdAsync(Model.Id);

                User.UserName = Model.UserName;
                User.Email = Model.Email;
                User.Address = Model.Address;

                IdentityResult Result = await UserManager.UpdateAsync(User);

                if(Result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach(var Error in Result.Errors)
                {
                    ModelState.AddModelError("", Error.Description);
                }
            }

            return View(Model);
        }
    }
}

PresentationLayer/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PresentationLayer.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark text-white">
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PresentationLayer/Views/Shared/_FormPartial.cshtml
@model Department

<form asp-controller="Department" asp-action="Create">
    <div class="form-group">
        <label asp-for="Code"></label>
        <input asp-for="Code" class="form-control">
        <span class="text-danger" asp-validation-for="Code"></span>
    </div>
    <br />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <br />
    <div class="form-group">
        <label asp-for="DateOfCreation"></label>
        <input asp-for="DateOfCreation" class="form-control">
        <span class="text-danger" asp-validation-for="DateOfCreation"></span>
    </div>

    <br />
    <input class="btn btn-primary" type="submit" value="Create" />
    <a class="btn btn-light" asp-controller="Department" asp-action="Index">Back To List</a>
</form>

PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PresentationLayer.styles.css" asp-append-version="true" />
    <style>
        .rounded-circle {
            width: 50px;
            height: 50px;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PresentationLayer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        @if(User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <p class="nav-link text-dark">@User.Identity.Name</p>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>